changelog:
  categories:
    - title: 🚀 Features
      labels:
        - "feature"
        - "enhancement"
    - title: 🐛 Bug Fixes
      labels:
        - "fix"
        - "bugfix"
        - "bug"
    - title: 🧰 Maintenance
      labels:
        - "chore"
        - "dependencies"
    - title: 📝 Documentation
      labels:
        - "documentation"
    - title: Other Changes
      labels:
        - "*"
